export const seoLandingPages = [
  {
    href: "/subscription-tracker",
    label: "Subscription tracker",
    title: "Subscription tracker",
    text: "Track subscriptions, renewals and recurring costs in one private place.",
  },
  {
    href: "/free-trial-reminder",
    label: "Free trial reminder",
    title: "Free trial reminder",
    text: "Review free trial end dates before the first paid charge.",
  },
  {
    href: "/bill-reminder",
    label: "Bill reminder",
    title: "Bill reminder",
    text: "Remember repeating bills, shared subscriptions and upcoming renewals.",
  },
  {
    href: "/no-bank-subscription-tracker",
    label: "No-bank tracker",
    title: "No-bank tracker",
    text: "Track recurring payments without linking your bank or creating an account.",
  },
  {
    href: "/manual-subscription-tracker",
    label: "Manual tracker",
    title: "Manual subscription tracker",
    text: "Add services yourself and keep subscription tracking private by design.",
  },
  {
    href: "/subscription-reminder-app",
    label: "Reminder app",
    title: "Subscription reminder app",
    text: "Use local reminders to review renewals and trial endings before charges arrive.",
  },
  {
    href: "/subscription-spending-tracker",
    label: "Spending tracker",
    title: "Subscription spending tracker",
    text: "Understand monthly recurring spend, limits and cancellation savings.",
  },
  {
    href: "/subscription-tracker-android",
    label: "Android tracker",
    title: "Subscription tracker for Android",
    text: "Track subscriptions on Android with PayClear's private, local-first app.",
  },
  {
    href: "/track-streaming-subscriptions",
    label: "Streaming tracker",
    title: "Track streaming subscriptions",
    text: "Keep streaming renewals, trials and shared plans visible before they charge again.",
  },
  {
    href: "/shared-subscription-bill-splitter",
    label: "Bill splitter",
    title: "Shared subscription bill splitter",
    text: "Split recurring subscriptions and shared plans without a spreadsheet.",
  },
  {
    href: "/subscription-cancellation-savings",
    label: "Savings calculator",
    title: "Subscription cancellation savings",
    text: "Estimate how much canceling unused subscriptions could save over time.",
  },
  {
    href: "/recurring-payment-tracker",
    label: "Recurring tracker",
    title: "Recurring payment tracker",
    text: "Track repeating payments, subscriptions and renewals in a private app.",
  },
  {
    href: "/subscription-tracker-without-plaid",
    label: "Without Plaid",
    title: "Subscription tracker without Plaid",
    text: "Track recurring payments manually without Plaid, bank sync or transaction scanning.",
  },
  {
    href: "/payclear-vs-bank-connected-trackers",
    label: "Tracker comparison",
    title: "PayClear vs bank-connected trackers",
    text: "Compare PayClear's manual privacy-first model with automatic bank-connected apps.",
  },
  {
    href: "/best-private-subscription-tracker",
    label: "Private tracker",
    title: "Best private subscription tracker",
    text: "Learn what makes a subscription tracker private and where PayClear fits.",
  },
  // New pages — US/CA focused
  {
    href: "/best-subscription-tracker-app",
    label: "Best tracker app",
    title: "Best subscription tracker app",
    text: "Find the best subscription tracker app for privacy, features and value in 2026.",
  },
  {
    href: "/subscription-manager-app",
    label: "Manager app",
    title: "Subscription manager app",
    text: "Organize all your recurring payments in one private subscription manager.",
  },
  {
    href: "/how-to-track-subscriptions",
    label: "How to track",
    title: "How to track subscriptions",
    text: "Step-by-step guide to finding, organizing and managing every recurring payment.",
  },
  {
    href: "/cancel-unused-subscriptions",
    label: "Cancel and save",
    title: "Cancel unused subscriptions",
    text: "Find forgotten subscriptions and estimate how much you can save by canceling.",
  },
  {
    href: "/free-trial-tracker-app",
    label: "Trial tracker",
    title: "Free trial tracker app",
    text: "Track free trial end dates so you never get charged for something you did not want.",
  },
  {
    href: "/subscription-tracker-app-free",
    label: "Free app",
    title: "Free subscription tracker app",
    text: "Track subscriptions for free with core reminders, dashboard and CSV export.",
  },
  {
    href: "/manage-recurring-payments",
    label: "Recurring payments",
    title: "Manage recurring payments",
    text: "Track bills, subscriptions and regular charges in one private dashboard.",
  },
  {
    href: "/stop-wasting-money-subscriptions",
    label: "Stop wasting money",
    title: "Stop wasting money on subscriptions",
    text: "Find unused subscriptions, review renewals, and make recurring spending intentional.",
  },
  {
    href: "/subscription-cost-calculator",
    label: "Cost calculator",
    title: "Subscription cost calculator",
    text: "Calculate monthly and yearly subscription costs, then plan practical savings.",
  },
  {
    href: "/family-subscription-manager",
    label: "Family plans",
    title: "Family subscription manager",
    text: "Organize shared plans, bill splits, and household renewal decisions.",
  },
  {
    href: "/subscription-tracker-no-login",
    label: "No login tracker",
    title: "Subscription tracker with no login",
    text: "Track renewals privately without a PayClear account or bank connection.",
  },
  {
    href: "/subscription-tracker-usa",
    label: "USA tracker",
    title: "Subscription tracker USA",
    text: "Track US subscriptions, free trials, and bills without a US bank connection.",
  },
  // Competitor comparison pages
  {
    href: "/payclear-vs-rocket-money",
    label: "vs Rocket Money",
    title: "PayClear vs Rocket Money",
    text: "Compare PayClear's private manual tracking with Rocket Money's bank-connected model.",
  },
  {
    href: "/payclear-vs-truebill",
    label: "vs Truebill",
    title: "PayClear vs Truebill",
    text: "Truebill (now Rocket Money) vs PayClear — bank scanning vs manual privacy-first tracking.",
  },
  {
    href: "/payclear-vs-mint",
    label: "vs Mint",
    title: "PayClear vs Mint",
    text: "A focused subscription tracker alternative for former Mint users without bank linking.",
  },
];
