export const seoLandingPages = [
  {
    href: "/subscription-tracker",
    label: "Subscription tracker",
    title: "Subscription tracker",
    text: "Track subscriptions, renewals and recurring costs in one private place.",
  },
  {
    href: "/free-trial-reminder",
    label: "Free trial reminder",
    title: "Free trial reminder",
    text: "Review free trial end dates before the first paid charge.",
  },
  {
    href: "/bill-reminder",
    label: "Bill reminder",
    title: "Bill reminder",
    text: "Remember repeating bills, shared subscriptions and upcoming renewals.",
  },
  {
    href: "/no-bank-subscription-tracker",
    label: "No-bank tracker",
    title: "No-bank tracker",
    text: "Track recurring payments without linking your bank or creating an account.",
  },
  {
    href: "/manual-subscription-tracker",
    label: "Manual tracker",
    title: "Manual subscription tracker",
    text: "Add services yourself and keep subscription tracking private by design.",
  },
  {
    href: "/subscription-reminder-app",
    label: "Reminder app",
    title: "Subscription reminder app",
    text: "Use local reminders to review renewals and trial endings before charges arrive.",
  },
  {
    href: "/subscription-spending-tracker",
    label: "Spending tracker",
    title: "Subscription spending tracker",
    text: "Understand monthly recurring spend, limits and cancellation savings.",
  },
  {
    href: "/subscription-tracker-android",
    label: "Android tracker",
    title: "Subscription tracker for Android",
    text: "Track subscriptions on Android with PayClear's private, local-first app.",
  },
  {
    href: "/track-streaming-subscriptions",
    label: "Streaming tracker",
    title: "Track streaming subscriptions",
    text: "Keep streaming renewals, trials and shared plans visible before they charge again.",
  },
  {
    href: "/shared-subscription-bill-splitter",
    label: "Bill splitter",
    title: "Shared subscription bill splitter",
    text: "Split recurring subscriptions and shared plans without a spreadsheet.",
  },
  {
    href: "/subscription-cancellation-savings",
    label: "Savings calculator",
    title: "Subscription cancellation savings",
    text: "Estimate how much cancelling unused subscriptions could save over time.",
  },
  {
    href: "/recurring-payment-tracker",
    label: "Recurring tracker",
    title: "Recurring payment tracker",
    text: "Track repeating payments, subscriptions and renewals in a private app.",
  },
  {
    href: "/subscription-tracker-without-plaid",
    label: "Without Plaid",
    title: "Subscription tracker without Plaid",
    text: "Track recurring payments manually without Plaid, bank sync or transaction scanning.",
  },
  {
    href: "/payclear-vs-bank-connected-trackers",
    label: "Tracker comparison",
    title: "PayClear vs bank-connected trackers",
    text: "Compare PayClear's manual privacy-first model with automatic bank-connected apps.",
  },
  {
    href: "/best-private-subscription-tracker",
    label: "Private tracker",
    title: "Best private subscription tracker",
    text: "Learn what makes a subscription tracker private and where PayClear fits.",
  },
];
